### ISSUE TITLE
[BUG]: npm run build fails

### ISSUE THREAD

**Issue by parmarpIBM** [merative/spm-ui-addon-devenv#20]
**Describe the bug**
The command npm run build fails after cloning the repo.  I get the following error:

ERROR in ./packages/carbon-addons-devenv/sample_renderers/index.js
Module not found: Error: Can't resolve './Logo' in '/opt/IBM/Curam/spm-ui-addon-devenv-1.0.0/packages/carbon-addons-devenv/sample_renderers'
 @ ./packages/carbon-addons-devenv/sample_renderers/index.js 12:0-26 15:8-12
 @ ./packages/carbon-addons-devenv/src/staticExports.js
 @ ./packages/carbon-addons-devenv/src/index.js
 @ multi ./public-path.js ./packages/carbon-addons-devenv/src/index.js

ERROR in ./packages/carbon-addons-devenv/sample_renderers/index.js
Module not found: Error: Can't resolve './PersonFolio' in '/opt/IBM/Curam/spm-ui-addon-devenv-1.0.0/packages/carbon-addons-devenv/sample_renderers'
 @ ./packages/carbon-addons-devenv/sample_renderers/index.js 11:0-40 14:15-26
 @ ./packages/carbon-addons-devenv/src/staticExports.js
 @ ./packages/carbon-addons-devenv/src/index.js
 @ multi ./public-path.js ./packages/carbon-addons-devenv/src/index.js

The class index.js above imports from './PersonFolio' and './Logo' whereas the folder name is all lowercase.  I updated the index.js to use lowercase to get the build to pass.

**To Reproduce**
clone the repo
update the .env and .env.development as per directions
execute npm ci
execute npm run build.  

**Expected behavior**
the build succeeds

**Comment by niambhscullion12** [comment]
Thanks so much for this issue. One of the team will investigate the issue. Please do bear with us, it is the Christmas period and we won't have a full team until mid January. 

Thanks, 
Niambh

**Comment by bdjos1** [comment]
Fixed on https://github.com/merative/spm-ui-addon-devenv/tree/feature/1.1.0_releaseCandidate branch and will be delivered in upcoming release
