### ISSUE TITLE
[BUG]: Doc Issue on Integrating Components with UIM

### ISSUE THREAD

**Issue by parmarpIBM** [merative/spm-ui-addon-devenv#21]
**Describe the bug**
When my UIM with the configured renderer launches the page to display the PersonFolio component, the spm-custom-carbon-addons-main.bundle.js is invoked and throws an error in the web console.   See attached screenshot.

The following page describes how to integrate carbon components: https://ibm.github.io/spm-ui-addon-devenv/integrate-addon-in-uim

It wasn't clear at first that the hooks directory inside 'custom-carbon-addons' needed to be updated to import/export from the 'carbon-addon-devenv' folder in order for this to work.  

**To Reproduce**
1. execute npm run build followed by npm run dev 
2. Launch the target UIM

**Expected behavior**
The PersonFolio widget appears in the target UIM

**Screenshots**
![Pasted Graphic](https://user-images.githubusercontent.com/72471459/146423284-309e887b-95a4-4992-b142-0fe4934bad4a.png)

**Comment by niambhscullion12** [comment]
Thanks so much for this issue. One of the team will investigate the issue. Please do bear with us, it is the Christmas period and we won't have a full team until mid January. 

Thanks, 
Niambh

**Comment by bdjos1** [comment]
Fixed on https://github.com/merative/spm-ui-addon-devenv/tree/feature/1.1.0_releaseCandidate branch and will be delivered in upcoming release
